#!/usr/awk
# convert the Radiator.log file to csv file for graphical exploitation
# see https://www.shellunix.com/awk.html for awk use
' BEGIN { print "Time,Temperature,Mode" }
$2 == "makeDecision" { print $1 "," $8 "," $5 } ' Radiator.log > Radiator.csv
